import { format } from 'date-fns';
import { formatInTimeZone } from 'date-fns-tz';

export interface CalendarEvent {
  id: string;
  teamId: string;
  title?: string;
  description?: string;
  startTime: Date;
  endTime: Date;
  attendees?: Array<{
    name: string;
    email?: string;
  }>;
  location?: string;
}

/**
 * RFC 5545 compliant line folding for ICS format
 * Lines longer than 75 octets must be folded using CRLF followed by a space
 */
function foldICSLine(line: string): string {
  if (line.length <= 75) {
    return line;
  }
  
  const result = [];
  let start = 0;
  
  // First line can be 75 chars
  result.push(line.substring(start, 75));
  start = 75;
  
  // Subsequent lines can be 74 chars (accounting for the leading space)
  while (start < line.length) {
    const end = Math.min(start + 74, line.length);
    result.push(' ' + line.substring(start, end));
    start = end;
  }
  
  return result.join('\r\n');
}

/**
 * Generate RFC 5545 compliant ICS file content with proper line folding
 */
export function generateICS(event: CalendarEvent): string {
  const formatICSDate = (date: Date): string => {
    // Ensure UTC format with Z suffix
    const utcDate = new Date(date.getTime());
    return format(utcDate, "yyyyMMdd'T'HHmmss'Z'");
  };

  const escapeICSText = (text: string): string => {
    return text
      .replace(/\\/g, '\\\\')
      .replace(/,/g, '\\,')
      .replace(/;/g, '\\;')
      .replace(/\n/g, '\\n')
      .replace(/\r/g, '');
  };

  const now = new Date();
  const uid = `${event.teamId}-${event.id}-${now.getTime()}@fairmeet`;
  
  const attendeesText = event.attendees
    ?.map(attendee => {
      const email = attendee.email ? ` (${maskEmail(attendee.email)})` : '';
      return `${attendee.name}${email}`;
    })
    .join(', ') || '';

  const description = [
    event.description || 'Team meeting scheduled through FairMeet',
    attendeesText ? `\\n\\nAttendees: ${attendeesText}` : '',
    '\\n\\nGenerated by FairMeet - Fair Meeting Scheduler for distributed teams'
  ].filter(Boolean).join('');

  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//FairMeet//Fair Meeting Scheduler//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'BEGIN:VEVENT',
    `UID:${uid}`,
    `DTSTAMP:${formatICSDate(now)}`,
    `DTSTART:${formatICSDate(event.startTime)}`,
    `DTEND:${formatICSDate(event.endTime)}`,
    `SUMMARY:${escapeICSText(event.title || 'FairMeet — Team Meeting')}`,
    `DESCRIPTION:${escapeICSText(description)}`,
    event.location ? `LOCATION:${escapeICSText(event.location)}` : null,
    'STATUS:TENTATIVE',
    'TRANSP:OPAQUE',
    'SEQUENCE:0',
    'END:VEVENT',
    'END:VCALENDAR'
  ].filter(line => line !== null);

  // Apply line folding to each line
  const foldedLines = lines.map(line => foldICSLine(line));
  
  return foldedLines.join('\r\n');
}

/**
 * Download ICS file
 */
export function downloadICS(event: CalendarEvent, filename?: string): void {
  const icsContent = generateICS(event);
  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `fairmeet-${format(event.startTime, 'yyyy-MM-dd-HH-mm')}.ics`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generate Google Calendar deep link
 */
export function generateGoogleCalendarLink(event: CalendarEvent): string {
  const formatGoogleDate = (date: Date): string => {
    return format(date, "yyyyMMdd'T'HHmmss'Z'");
  };

  const attendeesText = event.attendees
    ?.map(attendee => {
      const email = attendee.email ? ` (${maskEmail(attendee.email)})` : '';
      return `${attendee.name}${email}`;
    })
    .join(', ') || '';

  const description = [
    event.description || 'Team meeting scheduled through FairMeet',
    attendeesText ? `\n\nAttendees: ${attendeesText}` : '',
    '\n\nGenerated by FairMeet - Fair Meeting Scheduler'
  ].filter(Boolean).join('');

  const params = new URLSearchParams({
    action: 'TEMPLATE',
    text: event.title || 'FairMeet — Team Meeting',
    dates: `${formatGoogleDate(event.startTime)}/${formatGoogleDate(event.endTime)}`,
    details: description,
    ...(event.location && { location: event.location })
  });

  return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

/**
 * Open Google Calendar with event
 */
export function openGoogleCalendar(event: CalendarEvent): void {
  const url = generateGoogleCalendarLink(event);
  window.open(url, '_blank', 'noopener,noreferrer');
}

/**
 * Mask email for privacy
 */
export function maskEmail(email: string): string {
  const [local, domain] = email.split('@');
  if (!local || !domain) return email;
  
  const maskedLocal = local.length > 2 
    ? local.charAt(0) + '*'.repeat(Math.min(local.length - 1, 3))
    : local.charAt(0) + '*';
  
  return `${maskedLocal}@${domain}`;
}

/**
 * Test cases for different timezone scenarios
 */
export interface TestCase {
  name: string;
  startTime: Date;
  endTime: Date;
  timezone: string;
  description: string;
}

export function generateTestCases(): TestCase[] {
  const now = new Date();
  const baseDate = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1);

  return [
    {
      name: 'KST Standard Time',
      startTime: new Date(baseDate.getTime() + (14 * 60 * 60 * 1000)), // 2PM UTC = 11PM KST
      endTime: new Date(baseDate.getTime() + (15 * 60 * 60 * 1000)),   // 3PM UTC = 12AM KST+1
      timezone: 'Asia/Seoul',
      description: 'Evening meeting in Korea timezone with potentially long attendee list and detailed description to test RFC5545 line folding capabilities'
    },
    {
      name: 'PST/PDT Transition',
      startTime: new Date(2024, 2, 15, 10, 0, 0), // March 15, 2024 10:00 UTC (During DST transition)
      endTime: new Date(2024, 2, 15, 11, 0, 0),   // March 15, 2024 11:00 UTC
      timezone: 'America/Los_Angeles',
      description: 'Meeting during PST/PDT transition period - testing calendar compatibility across daylight saving time changes with detailed information'
    },
    {
      name: 'UTC Global Meeting',
      startTime: new Date(baseDate.getTime() + (12 * 60 * 60 * 1000)), // 12PM UTC
      endTime: new Date(baseDate.getTime() + (13 * 60 * 60 * 1000)),   // 1PM UTC
      timezone: 'UTC',
      description: 'Standard UTC meeting time for global teams - testing compatibility with various calendar applications including Google Calendar, Outlook, and Apple Calendar'
    },
    {
      name: 'Cross-Date Boundary Meeting',
      startTime: new Date(baseDate.getTime() + (23 * 60 * 60 * 1000)), // 11PM UTC
      endTime: new Date(baseDate.getTime() + (24 * 60 * 60 * 1000) + (30 * 60 * 1000)), // 12:30AM UTC+1
      timezone: 'Europe/London',
      description: 'Meeting crossing date boundary to test calendar applications handling of events spanning multiple days with British Summer Time considerations'
    }
  ];
}

/**
 * Generate test ICS files for QA validation across major calendar applications
 */
export function generateTestICSFiles(): { name: string; content: string; filename: string }[] {
  const testCases = generateTestCases();
  
  return testCases.map((testCase, index) => {
    const testEvent: CalendarEvent = {
      id: `test-${index + 1}`,
      teamId: 'qa-team',
      title: `QA Test: ${testCase.name}`,
      description: testCase.description,
      startTime: testCase.startTime,
      endTime: testCase.endTime,
      attendees: [
        { name: 'John Doe', email: 'john.doe@example.com' },
        { name: 'Jane Smith', email: 'jane.smith@company.org' },
        { name: 'Alex Johnson', email: 'alex.johnson@test.co.uk' }
      ],
      location: `Virtual Meeting (${testCase.timezone})`
    };

    return {
      name: testCase.name,
      content: generateICS(testEvent),
      filename: `fairmeet-qa-${testCase.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}.ics`
    };
  });
}

/**
 * Download all test ICS files for QA validation
 */
export function downloadAllTestFiles(): void {
  const testFiles = generateTestICSFiles();
  
  testFiles.forEach((file, index) => {
    setTimeout(() => {
      const blob = new Blob([file.content], { type: 'text/calendar;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      
      const link = document.createElement('a');
      link.href = url;
      link.download = file.filename;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    }, index * 500); // Stagger downloads to avoid browser blocking
  });
}

/**
 * Format time in specific timezone for display
 */
export function formatTimeInTimezone(date: Date, timezone: string): string {
  try {
    return formatInTimeZone(date, timezone, 'yyyy-MM-dd HH:mm:ss zzz');
  } catch (error) {
    console.warn(`Failed to format time in timezone ${timezone}:`, error);
    return format(date, 'yyyy-MM-dd HH:mm:ss') + ' UTC';
  }
}