// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imuoowrojmtaruhnnpgb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltdW9vd3Jvam10YXJ1aG5ucGdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDA4NTAsImV4cCI6MjA2OTI3Njg1MH0.8T0Kbi_2v5ti5RCf9PHfOeOzMvZo8pqP1vbbc-4oxMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});